config/routes.rb
Rails.application.routes.draw do

  root "products#index"

  resources :products

end

app/models/product.rb
class Product < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to product_path(@product), notice: "Product was successfully created"
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    if @product.save
      redirect_to products_path, notice: "Product was updated successfully"
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path, notice: "Product was deleted"
  end

  private
  def product_params
    params.require(:product).permit(
      :name,
      :description,
      :price,
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Products</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if notice %>
  <%= notice %>
<% end %>
<br>

<%= yield %>

</body>
</html>

app/views/products/edit.html.erb
<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :price %>
  <%= f.text_field :price %>

  <%= f.submit %>
<% end %>

app/views/products/index.html.erb
<%= link_to "New Product", new_product_path %>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>
        Name
      </th>
      <th>
        Description
      </th>
      <th>
        Price
      </th>
      <th>
        Date created
      </th>
      <th>
        Date last updated
      </th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
    <tr>
      <td>
        <%= link_to product.name, product_path(product) %>
      </td>
      <td>
        <%= product.description %>
      </td>
      <td>
        <%= product.price %>
      </td>
      <td>
        <%= product.created_at %>
      </td>
      <td>
        <%= product.updated_at %>
      </td>
    </tr>
    <% end %>

  </tbody>
</table>

app/views/products/new.html.erb
<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :price %>
  <%= f.text_field :price %>

  <%= f.submit %>
<% end %>

app/views/products/show.html.erb
<h1>
  <%= @product.name %>
</h1>
<br>

<table>
  <thead>
    <tr>
      <th>
        Description
      </th>
      <th>
        Price
      </th>
      <th>
        Date created
      </th>
      <th>
        Date last updated
      </th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td>
        <%= @product.description %>
      </td>
      <td>
        <%= @product.price %>
      </td>
      <td>
        <%= @product.created_at %>
      </td>
      <td>
        <%= @product.updated_at %>
      </td>
      <td>
        <%= link_to "edit", edit_product_path %>
      </td>
      <td>
        <%= link_to "delete", product_path(@product), method: :delete, data: {confirm: "are you sure?"} %>
      </td>
    </tr>
  </tbody>
</table>